wall_follower:
  ros__parameters:
    scan_topic: "/scan"
    drive_topic: "/vesc/high_level/input/nav_0" #"/drive"
    side: -1
    velocity: 1.0
    desired_distance: 0.5
    lookahead_distance: 2.0
      #lookahead_distance: 2.0
